# Generated by Django 3.0.3 on 2020-07-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200719_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentOfficers',
            new_name='DepartmentOfficer',
        ),
    ]
