# Generated by Django 3.0.3 on 2020-07-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200719_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentofficer',
            name='department_name',
            field=models.CharField(choices=[('Library', 'Library'), ('Workshop', 'Workshop'), ('MustSo', 'MustSo'), ('Laboratories', 'Laboratories'), ('Head Of Department', 'Head Of Department'), ('Catering Office', 'Catering Office'), ('Sports and Games', 'Sports and Games'), ('Accomodation', 'Accomodation'), ('Accounts Office', 'Accounts Office')], max_length=100),
        ),
    ]
