# Generated by Django 3.0.3 on 2020-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200731_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
