# Generated by Django 3.0.3 on 2020-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200801_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
