# Generated by Django 3.0.3 on 2020-07-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='department_name',
            field=models.CharField(default='Accomodation', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='accountsoffice',
            name='department_name',
            field=models.CharField(default='AccountsOffice', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='cateringoffice',
            name='department_name',
            field=models.CharField(default='CateringOffice', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='department_name',
            field=models.CharField(default='HeadOfDepartment', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='laboratories',
            name='department_name',
            field=models.CharField(default='Laboratories', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='library',
            name='department_name',
            field=models.CharField(default='Library', max_length=150),
        ),
        migrations.AddField(
            model_name='mustso',
            name='department_name',
            field=models.CharField(default='MustSo', max_length=150),
        ),
        migrations.AddField(
            model_name='sportsgames',
            name='department_name',
            field=models.CharField(default='SportsGames', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='department_name',
            field=models.CharField(default='Workshop', max_length=150, unique=True),
        ),
    ]
