# Generated by Django 3.0.3 on 2020-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20200722_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accountsoffice',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cateringoffice',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laboratories',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='library',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mustso',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sportsgames',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='lent_date',
            field=models.DateField(auto_now=True),
        ),
    ]
