# Generated by Django 3.0.3 on 2020-08-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200804_2332'),
        ('departments', '0006_auto_20200804_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deanofstudents',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Student'),
        ),
    ]
